### ISSUE TITLE
go.mod retract directive not valid in Go 1.15

### ISSUE THREAD

**Issue by marten-seemann** [protocol/.github#100]
https://github.com/ipfs/go-ipfs-provider/pull/36/checks?check_run_id=2603002796 fails on Go 1.15, but succeeds on Go 1.16, because the [go.mod](https://github.com/ipfs/go-ipfs-provider/blob/master/go.mod) uses `retract`, which was added in Go 1.16.

**Comment by marten-seemann** [comment]
One option to solve this would be to introduce a config option to set the minimum Go version in `config.json`, and modify the `go test` workflow accordingly.

Thoughts, @mvdan and @Stebalien?

**Comment by mvdan** [comment]
Hm, that's a very unfortunate error. Retracting versions shouldn't affect `go test`, so I would hope that we wouldn't need to alter the versions of Go to test with in `config.json`.

Here's another idea: when propagating the CI files, if we by default run CI on Go 1.15 and 1.16, and that module's go.mod declares `go 1.16`, then we only test on 1.16. This makes sense to me at a high level - if a module means to still support 1.15, then declaring 1.16 on their go.mod makes little sense, as you'd only do that if you wanted to start using features added in 1.16, such as new language features.

**Comment by mvdan** [comment]
FYI I've asked about this (in my opinion reasonable) module setup scenario in the #modules channel over on the Gophers slack. The people developing modules usually hang around there, so I expect to get some sort of helpful feedback soon. Maybe not until Tuesday, given that Monday is a holiday in the US.

**Comment by Stebalien** [comment]
I like the idea of reading the go.mod file, but changing the go.mod file won't cause the CI files to update (unless we have some form of trigger there?). I'm also fine dropping go 1.15 at this point...

**Comment by marten-seemann** [comment]
> I like the idea of reading the go.mod file, but changing the go.mod file won't cause the CI files to update (unless we have some form of trigger there?).

We wouldn't be able to prevent the workflow from running, but we could have a step that runs before the `go test` step, which could abort the run early. Not very elegant though.

What we could also do is the following:
* When deploying, we parse the go.mod file, and deploy the corresponding go-test workflow.
* If a repository decides to drop Go 1.15 at a later point, it has to remove it from the go-test workflow as well. That would make sure that the copy workflow wouldn't try to "update" the workflow back to its prior state at a later point.

Another option: Assume that this will be the last backwards-incompatible change to go.mod and this problem will go away as soon as Go 1.17 is released (which is in 2.5 more months), or earlier if we decide to drop 1.15.

**Comment by mvdan** [comment]
Why not do both at the same time? That is, do the detection of the go version in go.mod when we propagate changes, but also when CI runs.

For a module that declares `go 1.16` in its go.mod, the common scenario will be that a previous CI propagation already removed the part about running on Go 1.15.x.

In some rare cases where a module suddenly bumps from `go 1.15` to `go 1.16`, it might be weeks until another CI propagation happens. This is where the extra check as part of CI would happen; until the next propagation removes Go 1.15.x, its job would simply exit early, in less than 10s or so. But again, this should be rare, which would be good as it could be confusing.

**Comment by marten-seemann** [comment]
We don't really care about this any more, as we've dropped Go 1.15 support a while ago.
