### ISSUE TITLE
Don't over-write "sync" branches with new commits

### ISSUE THREAD

**Issue by Stebalien** [protocol/.github#114]
We often push new commits to ci deploy branches to try to fix CI. However, the current logic will overwrite these changes when deploying updates. Ideally, we'd only remove commits made by the bot.

**Comment by marten-seemann** [comment]
Fair point. How do you suggest new updates are deployed to those repos then? Should we open a new PR for every change?

**Comment by Stebalien** [comment]
The simplest is probably to open a new PR. For simplicity, we can just
close the old one (but don't delete it). The main problem with that is
the branch names...

Alternatively, if the PR has been "modified" by other authors, append
the new changes as new commits. Not sure how hard that would be.

**Comment by marten-seemann** [comment]
> The simplest is probably to open a new PR. For simplicity, we can just
close the old one (but don't delete it). The main problem with that is
the branch names...

There are 2 options:
1. We could use `sync-<SHA>` as a branch name, that should be unambiguous. Closing the old PR might turn out to be more complicated though.
1. We could first check if the branch exists, and if so, delete it. Afaik, pushing that deletion to GitHub would close the PR. 

> Alternatively, if the PR has been "modified" by other authors, append
the new changes as new commits. Not sure how hard that would be.

That sounds pretty complicated, as there might be merge conflicts between the first and the second change.

**Comment by mvdan** [comment]
How about, if someone messed with the PR, we assume they're now in control and do nothing? We could perhaps check if this is the case by seeing if the last push to the branch was done by the bot, or if the last commit in the branch was committed by the bot.

If a human is in control, then they are in charge of either adding the newer changes themselves, or merging/closing the PR and triggering the deployment automation again.

**Comment by Stebalien** [comment]
> 1. We could first check if the branch exists, and if so, delete it. Afaik, pushing that deletion to GitHub would close the PR. 

Well, my hope was to _not_ delete it if modified.

>> Alternatively, if the PR has been "modified" by other authors, append
> the new changes as new commits. Not sure how hard that would be.
>
> That sounds pretty complicated, as there might be merge conflicts between the first and the second change.

Doesn't the deploy script just add new files and commit them? There
shouldn't be any conflicts.

**Comment by marten-seemann** [comment]
Assuming that we don't manually modify the workflow files in the PR (which we really, really shouldn't), we could check out the sync branch, delete all commits authored by web3-bot, and replace them by updated commits.

**Comment by Stebalien** [comment]
Yeah. That's what I was thinking. Or we could just keep the old commits, overwrite the files, and add new commits. Both should work.

**Comment by mvdan** [comment]
This seems fine to me - I'd just make sure that PR descriptions have a warning against amending commits authored by the bot, because the bot will overwrite them. Some people's workflows with PRs involve amending previous commits or rebasing instead of just appending extra commits.

**Comment by galargh** [comment]
Unified CI will try to be nicer now (see https://github.com/pl-strflt/uci/blob/651757f60e8d0df173890f1e8a4d645d4c391bf1/.github/workflows/process.yml#L138-L150). By default, it'll try to rebase. It'll only revert to forced reset if the rebase cannot be executed cleanly.
