### ISSUE TITLE
Detect missing and misspelled repos

### ISSUE THREAD

**Issue by Stebalien** [protocol/.github#128]
This isn't _critical_, but it would be nice if we could detect missing and misspelled repos in the `config.json`.

**Comment by marten-seemann** [comment]
https://github.com/protocol/.github/blob/master/.github/workflows/stale-repos.yml should catch those. Doesn't it?

**Comment by mvdan** [comment]
The typo fix was less than an hour after the line was added, but the check runs every 6h. I assume we can't run it more often without starting to run into rate limits. I'd say this is working as intended - we would have caught the typo within hours.

**Comment by marten-seemann** [comment]
> The typo fix was less than an hour after the line was added, but the check runs every 6h. I assume we can't run it more often without starting to run into rate limits.

We could run it a lot more often, this job just takes 30s, so there's no risk of being rate-limited here, even if we ran it every 30 min or so (I assume).

> I'd say this is working as intended - we would have caught the typo within hours.

We should probably run this job on `pull_request` too (or only?), that would've caught the problem immediately.

**Comment by mvdan** [comment]
SGTM, we don't have that many PRs anyway.

**Comment by Stebalien** [comment]
Running on PR is what I'm looking for. But can we just check _changed_ lines? I.e., diff the json files and check any added repos?

**Comment by marten-seemann** [comment]
Right, we still need to run it as a cron, as repos might be deleted at any time.

> But can we just check changed lines? I.e., diff the json files and check any added repos?

That should be possible, but it might be a bit tricky to parse the diff between two JSON versions.

**Comment by Stebalien** [comment]
Eh, I'd parse the json first, then use something like `comm` to compare.

**Comment by marten-seemann** [comment]
TIL: `comm` :) That definitely makes more sense.

Would you mind updating the workflow?

**Comment by Stebalien** [comment]
Sure. I'll take a stab at it.
