### ISSUE TITLE
complain if running `go test ./...` results in unstaged git changes

### ISSUE THREAD

**Issue by mvdan** [protocol/.github#132]
For example, if running `go test ./...` on a cleanly checked out Go module results in a modified testdata file. That should never happen, at least not if that testdata file is checked into git.

This happened just now in go-car: https://github.com/ipld/go-car/pull/181

A single `go test ./...` would work, but we'd append to a testdata file instead of replacing it, so a second `go test ./...` would fail.

This went unnoticed for a few hours, until I was developing code locally and ran into it when iterating on a code change.

I think this has an easy fix. We already check that operations like `go mod tidy` and `gofmt -l -w .` don't result in unstaged git changes, so we should apply the same rule to all forms of `go test ./...`.

cc @marten-seemann @Stebalien @masih

**Comment by marten-seemann** [comment]
Never encountered an issue like that myself, but your reasoning certainly is reasonable.

One thought about temporary files: A test might write temporary data to a file, and a poorly written test might choose the working directory for that. But there's really no excuse for not cleaning up your temporary data, so a test failure can be justified in that case as well.

Do you want to send us a PR?

**Comment by mvdan** [comment]
Complaining on extra files in the repo which aren't gitignored is also something I'd do, but it doesn't seem as pressing to me, and might cause more annoyances to other repos.

I'll try to send a PR next week.

**Comment by mvdan** [comment]
> I'll try to send a PR next week.

I clearly didn't do this; this issue is up for grabs.
