### ISSUE TITLE
decide what to do with Codecov

### ISSUE THREAD

**Issue by marten-seemann** [protocol/.github#14]
Currently, we only upload to Codecov is there's a `codecov.yml` in the repository: https://github.com/ipld/.github/blob/93f9b881a3420019d5aa9114c61c6f82c8311d78/workflow-templates/go-test.yml#L31-L41

Most of our repos don't have that, and they still use Codecov. I suggest to always upload to Codecov, while at the same time taming Codecov as described in our [Best Practices](https://github.com/ipld/ipld/blob/master/best-practices/go-ci.md#using-code-coverage-tools), i.e. preventing it from failing our builds and posting coverage reports under every single PR.

cc @mvdan @Stebalien

**Comment by Stebalien** [comment]
SGTM!

**Comment by mvdan** [comment]
SGTM too, as long as it doesn't significantly slow down CI. It's then up to each repo to decide if they want to use or expose the data prominently.

Also, perhaps limit this feature to pushes to branches, not PR builds. That would save a bit of work for PR builds, which we want to be fast to make it easier to contribute.

**Comment by marten-seemann** [comment]
@mvdan Which part are you worried about? Running test with -cover? I’ve never benchmarked it, but I thought it’s pretty low overhead, isn’t it?
Shipping the coverage report to Codecov is just uploading a small text file, so the performance impact should be negligible.

**Comment by mvdan** [comment]
I'm mainly worrying about the codecov action, yeah. Sometimes you assume these things are fast and they only upload a single file, but they might take multiple seconds in practice :)

**Comment by marten-seemann** [comment]
I've applied the Codecov config from our [Best Practices](https://github.com/ipld/ipld/blob/master/best-practices/go-ci.md#using-code-coverage-tools) to the IPLD and libp2p org, and it seems to work.
