### ISSUE TITLE
consider running go-compat

### ISSUE THREAD

**Issue by marten-seemann** [protocol/.github#188]
go-libp2p-core currently runs a `go-compat` workflow: https://github.com/libp2p/go-libp2p-core/blob/master/.github/workflows/go-compat.yml
That workflow is rather annoying, because it 1. fails your build if you change the API and 2. it doesn't tell you why (you have to look into the output of the workflow run).

Would it be a good idea to run `go-compat` on all our repos, but instead of failing the build, the bot would comment on the PR (at least if any non-compatible changes are made)?

**Comment by mvdan** [comment]
Isn't backwards compatibility with semver already guaranteed if we implement https://github.com/protocol/.github/issues/158? I would definitely prefer upstream tools like gorelease or apidiff over gocompat.

**Comment by mvdan** [comment]
> That's about applying semver correctly. This suggestion is about alerting people (authors and, more importantly, reviewers) about breaking changes a PR might introduce, just to increase visibility.

I see. I would hope we could do that via the same workflow or tools that we'd use for releases.

Fully agreed that this suggestion/alert should be a comment, in any case, not a status check.

**Comment by marten-seemann** [comment]
`gorelease` pulls the latest version (or, if you specify it, any tagged version) from the module proxy, I don't think there's a way to make this work as a comparison to `master`. I don't have any experience with `apidiff`.

**Comment by mvdan** [comment]
Does `gorelease -base=master` not work?

An alternative would be to work out what the master version is via `go list`:

    gorelease -base=$(go list -m -f {{.Version}})

**Comment by marten-seemann** [comment]
Just tried it in go-tcp-transport:
```
 ~/src/go/src/github.com/libp2p/go-tcp-transport | master >
❯ gorelease -base=master
# summary
Base version: v0.2.8-0.20210817144700-2329e01cd30a (master)
Cannot suggest a release version.
Can only suggest a release version when compared against the most recent version of this major: v0.2.7.
```

**Comment by mvdan** [comment]
I'd suggest opening an issue upstream, to see what the maintainer (Jay) has to say about this use case. He's probably thought about it, but with the tool still being experimental, maybe the UX is a bit rough.

**Comment by marten-seemann** [comment]
`go-compat` is now run as part of the release checker workflow, so I believe we can close this issue.
