### ISSUE TITLE
update to Go 1.18

### ISSUE THREAD

**Issue by marten-seemann** [protocol/.github#193]
The update to Go 1.18 will be an interesting one, as it adds generics. It is safe to assume that many developers will want to use these shiny new language features right away.

This poses a bit of a problem, as using generics requires the Go version in go.mod to be 1.18. However, when we deploy the next Go version bump, the go.mod version will be 1.17 (we always support the most recent two Go versions).

After discussing this with @mvdan offline, we came to the following conclusion:
* People are free to bump the Go version in go.mod manually, if they want to use generics. Having `go-test` test both 1.17 and 1.18 makes sure that we keep our backwards-compatibility guarantees.
* For the Go version update after that (1.19), we'll have to change our upgrade logic in https://github.com/protocol/.github/blob/130b30b68dee0a13da5c74ea398cec3fde640765/.github/workflows/copy-workflow.yml#L109
This can be as simple as grepping for 1.17 in `go-test`.

**Comment by mvdan** [comment]
> For the Go version update after that (1.19), we'll have to change our upgrade logic in

Can you please expand on this, for the sake of clarity? Because the "go.mod version bump" logic on its own will still work just fine. The only bit we'd skip is `go fix ./...`, but luckily that's largely unused these days.

**Comment by marten-seemann** [comment]
Yes, my only concern was that the `if` code block would not be executed for repositories that manually bumped the version in go.mod. What `go fix` will or will not do for Go 1.19 we can't know at this point, can we?

**Comment by mvdan** [comment]
That's true, though the release notes would be pretty clear about whether or not `go fix` starts doing important things again.

**Comment by marten-seemann** [comment]
True, my point is, we don't have to worry about this. Looking at the Go versions in `go-test.yml` will be a more reliable way to detect if we're upgrading a repository, so we can just use that.

**Comment by mvdan** [comment]
That seems fine. My 2c is that it's possible that some users will tinker with those files manually on a temporary basis as needed, like Steven with that msys shell bit, so I don't think it will be as reliable as you think. Maybe we should start leaving behind a sentinel file of some sort, like `.github/.protocol-ci-version` containing a simple version like `go1.17-v1`.

**Comment by marten-seemann** [comment]
Steven’s msys bit would be overwritten the next time the copy workflow runs (e.g. when we add any new repo to config.json).
Our current setup doesn’t really allow _any_ changes to the yml files.

**Comment by galargh** [comment]
I think this one can be closed now since we've updated to Go 1.18 already.
