### ISSUE TITLE
Auto-deploy CI to dependencies when they're added

### ISSUE THREAD

**Issue by Stebalien** [protocol/.github#23]
We'll occasionally make some fancy new library and add it as a dependency to one of our projects but fail to actually setup CI.

We should add a action that:

1. Checks that all (transitive) go.mod dependencies housed in one of our orgs has CI correctly configured.
2. If not, fails CI, and makes a PR to _deploy_ CI to that repo.

This should help prevent this from happening in the future.

**Comment by galargh** [comment]
An alternative approach that came to mind after reading this would be to create a workflow in this repository that:
1. Fetches all Go repositories that were created recently - we can do that through GraphQL API by checking `createdAt` and `languages` properties on the repositories.
1. Checks which repos are not in the unified CI config yet.
1. Creates a PR/multiple PRs to unified CI for them and tags the owners.
