### ISSUE TITLE
run `go test` with `-shuffle`

### ISSUE THREAD

**Issue by marten-seemann** [protocol/.github#237]
This shuffles the test execution order, and allows us to detect tests where
1. test success depends on the execution order of tests
2. tests might fail if executed with `-count=2` (e.g. because one test fails to properly clean up)

This flag was introduced in Go 1.17, so the easiest thing is to wait until we drop Go 1.16.

**Comment by mvdan** [comment]
> tests might fail if executed with `-count=2` (e.g. because one test fails to properly clean up)

I think `-shuffle` would help catch some instances of this, but not others, e.g. when a test's failure to clean up conflicts only with a second run of itself.
