### ISSUE TITLE
Enable local workflow testing

### ISSUE THREAD

**Issue by galargh** [protocol/.github#238]
Having to use `testing` branch to test the workflows makes the feedback loop quite long. I think it might be worth investing some time in setting up a local testing environments for GitHub Actions workflows. 

https://github.com/nektos/act looks interesting.

**Comment by mvdan** [comment]
Sounds interesting indeed, but that's always going to be reverse-engineered unless Microsoft/GitHub write this themselves. The only way to truly test if stuff is working, right now, is by doing git pushes.

There's always going to be an aspect that you can't properly test locally either - the real GitHub API, the tokens stored in secrets, the github users involved, etc.

**Comment by galargh** [comment]
Yes, I agree 100% with that. The idea is to treat it as an additional testing layer rather than replacement. I could imagine such local setup discovering some issues with syntax, paths, etc. I'd just want it to tell me - your yamls are OK, there's a high chance they are going to execute on GitHub actions too, now push your changes to the `testing` branch and verify that they actually do what you expected them to.

**Comment by mvdan** [comment]
That's fair, just wanted to get a common understanding of why the testing branch can't really be replaced right now :)

**Comment by marten-seemann** [comment]
> I'd just want it to tell me - your yamls are OK

That one can be solved by putting a yamllint in a git hook. Feel free to commit your hooks as well (e.g. by following the pattern from https://github.com/lucas-clemente/quic-go/tree/master/.githooks).

Of course this doesn't tell you if it's valid GitHub Actions syntax, so probably my comment is slightly off-topic :)

**Comment by mvdan** [comment]
To add to it - I'm sure there are json schemas for github actions/workflows, so that could get you a bit further away than just checking YAML syntax.

**Comment by galargh** [comment]
In practice, nothing beats testing on GitHub. In https://github.com/pl-strflt/uci, we can manually trigger release workflows from any branch, with any repository as a target, with any inputs. This should vastly simplify testing as it makes it easier to adjust the testing scenarios to feature needs.
