### ISSUE TITLE
automerge is getting blocked by review requirements

### ISSUE THREAD

**Issue by marten-seemann** [protocol/.github#249]
![image](https://user-images.githubusercontent.com/1478487/145674329-42a16290-be52-4d6b-af73-d64504bf75d1.png)

I'm not sure if there's any way around this, but it would be really nice if we could somehow overwrite the review requirement for PRs opened by `web3-bot`. @galargh, any ideas?

**Comment by mvdan** [comment]
I don't think there's a quick way around this; we could make the bot an administrator so it can skip the checks, but that seems like a can of worms.

As an alternative, the bot has write permissions, so I wonder if we could have a second bot approve the changes. Adds more steps and setup, but seems safer than giving a bot admin permissions or dropping the safety requirements entirely.

Another option, and what I would say is best, is to obey the repo's protections. If I've set up the repo to require approvals from maintainers, I would be surprised if our bots were engineered to ignore those. Even for CI changes which are presumably safe.

**Comment by galargh** [comment]
This issue was transferred to https://github.com/pl-strflt/uci/issues/37 in preparation for archiving of this repository.
