### ISSUE TITLE
Setting up unified CI for rust repos

### ISSUE THREAD

**Issue by galargh** [protocol/.github#251]
Similarly to https://github.com/protocol/.github/issues/235, it would be great to have a common way of setting up CI for rust repos too. 

I'm creating this issue now to make sure we take into account rust-specific needs when we work on making the unified CI framework more customisable(to support JS workflows initially).

@laudiacay @mxinden Do you have any ideas/examples of what kind of workflows we might want to consider common in the rust world?

**Comment by mxinden** [comment]
Thanks @galargh tracking this!

For the reference, [rust-libp2p's workflow](https://github.com/libp2p/rust-libp2p/blob/master/.github/workflows/ci.yml) which served us well thus far.

A couple of tools which I think should be standard across repositories:

- rust-fmt
- cargo clippy
- cargo doc with intra-doc check
- cargo build (including benchmarks)
- cargo test (including benchmarks)
- build and test on WASM (if repo targets WASM)

**Comment by laudiacay** [comment]
Seconded on this! Figuring out workspaces and features being handled
correctly is also important but may vary by repo.

**Comment by galargh** [comment]
This issue was transferred to https://github.com/pl-strflt/uci/issues/38 in preparation for archiving of this repository.
