### ISSUE TITLE
Detect breaking changes

### ISSUE THREAD

**Issue by Stebalien** [protocol/.github#27]
CI should detect API breaking changes and leave comments indicating these breaking changes in the code. The merge doesn't have to be blocked, but these changes should at least be called out.

**Comment by mvdan** [comment]
https://pkg.go.dev/golang.org/x/exp/cmd/gorelease already implements most of this, so we could piggyback off of it.

I'd even consider failing CI if the breakage is obvious, and there's already a stable tag in the current major semver version. To work around it, one would have to bump the semver major version in the current module path, e.g. from `module foo/bar/v2` to `module foo/bar/v3`. Breaking changes would then be ignored until a tag like `v3.0.0` is made.

**Comment by galargh** [comment]
Is the ask here to detect breaking changes on every PR or has this request already been satisfied with running the checks before a tag release (as part of the versioning workflow)?

**Comment by laurentsenta** [comment]
We're assuming this request has been satisfied with running the checks before a tag release,
please re-open if not!
