### ISSUE TITLE
Release checker failed with no log

### ISSUE THREAD

**Issue by Kubuxu** [protocol/.github#291]
I'm trying to release go-ds-badger2.

https://github.com/ipfs/go-ds-badger2/runs/4943329674?check_suite_focus=true

As I need the tag for an external contributor (and they are waiting for it for a while) I'm creating the tag manually.

**Comment by galargh** [comment]
I see you merged the PR without the comment from the release checker (PR: https://github.com/ipfs/go-ds-badger2/pull/54). I also see that it worked as expected for a second bump (PR: https://github.com/ipfs/go-ds-badger2/pull/55).

I haven't seen a report like that before which makes me think it might have been some network issue on the worker side. I think using `Re-run all jobs` might have helped in this case:
<img width="159" alt="Screenshot 2022-02-01 at 10 04 28" src="https://user-images.githubusercontent.com/6688074/151940270-84cef705-b45f-43ce-9bb6-8f9e6e93eb2f.png">

I'll keep an eye out in case it's a more common issue.

**Comment by Kubuxu** [comment]
Sorry, I should have written an update. The issue was that `version.json` was v0.1.1, someone tagged v0.1.2 manually, I wasn't aware of that and bumped the version file to v0.1.2 which failed, then I noticed the te v0.1.2 tag which worked.

**Comment by galargh** [comment]
Got it, thanks for the explanation :)
