### ISSUE TITLE
automerge never seems to succeed

### ISSUE THREAD

**Issue by achingbrain** [protocol/.github#298]
In the js repos added to unified ci, the automerge workflow never finishes:

https://github.com/libp2p/js-libp2p-webrtc-star/runs/5288097801?check_suite_focus=true
https://github.com/libp2p/js-libp2p-tcp/runs/4817272253?check_suite_focus=true
https://github.com/libp2p/js-libp2p-mplex/runs/4850836537?check_suite_focus=true
etc

It looks like the `lewagon/wait-on-check-action` is defined in a job called `automerge` that [waits](https://github.com/protocol/.github/blob/master/templates/.github/workflows/automerge.yml#L43) for a workflow called `automerge` to finish before it moves on to the [merge step](https://github.com/protocol/.github/blob/master/templates/.github/workflows/automerge.yml#L44), but that never seems to happen?  Should it be waiting for [test & maybe release](https://github.com/protocol/.github/blob/master/templates/.github/workflows/js-test-and-release.yml#L10) instead?

Also, some of the projects have extra CI workflows (testing examples, etc), how can we wait for those too before merging CI config updates?

**Comment by galargh** [comment]
Sorry for not being more vocal about it. This issue has already been addressed in https://github.com/protocol/.github/pull/278. It will be included in the next major release of unified CI.

As for the automerge job itself. It is only intended to automerge PRs created by `web3-bot` where the last commit was made by `web3-bot` (in my opinion we could get rid of this second clause). It is currently split between 2 jobs `automerge-check` and `automerge`. All the first one does is to check if the last commit was made by `web3-bot` (even if we wanted to preserve this check, I think we could just do it as a step of the second job instead). The second job, waits for all the checks to finish apart from the one called `automerge` - this catches any checks defined outside unified CI framework too (see https://github.com/lewagon/wait-on-check-action#running-workflow-name). The problem with the current version of `wait-on-check-action` we use is that it considers `skipped` outcome as failure and we'd want it to be treated as success.

If you're interested in automerge functionality for PRs other than CI config updates, [GitHub auto-merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request) functionality should be the starting point.

**Comment by galargh** [comment]
This is fixed now as https://github.com/protocol/.github/pull/278 made it to `master` through https://github.com/protocol/.github/pull/314.
