### ISSUE TITLE
complain if a version is appended to version.json

### ISSUE THREAD

**Issue by mvdan** [protocol/.github#302]
I reviewed and approved https://github.com/ipld/go-codec-dagpb/pull/37 to bump the semver bugfix version, and it worked when merged - the tag appeared etc. I just didn't notice that the git diff was adding one object key-value, rather than replacing the existing one.

I get that, semantically, it's the same - when decoding, the second key-value wins. Still, to avoid confusion, I think the versioning workflow should reject any `version.json` that isn't exactly an object with one `version` key.

**Comment by marten-seemann** [comment]
This could be part of the release-checker workflow. It could then report a malformed version.json on the PR.

**Comment by galargh** [comment]
This issue was transferred to https://github.com/pl-strflt/uci/issues/41 in preparation for archiving of this repository.
