### ISSUE TITLE
update staticcheck

### ISSUE THREAD

**Issue by marten-seemann** [protocol/.github#310]
Staticcheck v0.3.0 was released: https://github.com/dominikh/go-tools/releases/tag/2022.1.

Looks like they also have a dedicated GitHub Action now, so we can simplify our `go-check` a bit. We should probably test that it correctly works with GitHub's code annotations first.

**Comment by dominikh** [comment]
> We should probably test that it correctly works with GitHub's code annotations first.

It should. We emit the necessary magic to install [problem matchers](https://github.com/dominikh/staticcheck-action/blob/master/matchers.json).

**Comment by galargh** [comment]
This was done here: https://github.com/protocol/.github/pull/311
