### ISSUE TITLE
Allow repositories to opt-in to get updates from next branch

### ISSUE THREAD

**Issue by galargh** [protocol/.github#312]
This could be used to do better testing of upcoming changes for example

**Comment by laurentsenta** [comment]
We would like to let a repo subscribe to any particular branch on the repo,
it does interact with the other [issue related to removing the next branch](https://github.com/protocol/.github/issues/313).

**Comment by galargh** [comment]
With https://github.com/pl-strflt/uci, this is possible by simply changing the version/branch the reusables refer to in the target repo.
