### ISSUE TITLE
Document what is a Unified CI Relase and how we communicate it

### ISSUE THREAD

**Issue by galargh** [protocol/.github#317]
1. Create a PR from `next` to `master`. E.g. https://github.com/protocol/.github/pull/314
1. Look through the changes introduced in the PR.
1. Create a release announcement. E.g. https://www.notion.so/pl-strflt/Unified-CI-Release-2022-04-04-c8ec2818764445618bec80f7739bf883
1. Share the release announcement on #ip-productivity channel a couple of days ahead of the release.
1. Create an email announcement. E.g. https://www.notion.so/pl-strflt/Unified-CI-Release-2022-04-04-c8ec2818764445618bec80f7739bf883
1. Send the email to shipped@ on the day of the release.
1. Merge the release PR to `master`.
1. Make sure the dispatch workflow and copy workflows succeeded. E.g. ...
1. Wait for a bit and check how many unmerged PRs from web3-bot there are.

**Comment by laurentsenta** [comment]
1. Review packages & modules updates (#372)
1. Check the stale repos workflow
  * for example https://github.com/protocol/.github/runs/7972743573?check_suite_focus=true 
  * Make sure the workflow is green (remove stale or archived repositories)
1. Create a PR from `next` to `master`. E.g. https://github.com/protocol/.github/pull/314
1. Look through the changes introduced in the PR.
1. Create a release announcement. E.g. https://www.notion.so/pl-strflt/Unified-CI-Release-2022-04-04-c8ec2818764445618bec80f7739bf883
1. Share the release announcement on #ip-productivity channel a couple of days ahead of the release.
1. Create an email announcement. E.g. https://www.notion.so/pl-strflt/Unified-CI-Release-2022-04-04-c8ec2818764445618bec80f7739bf883
1. Send the email to shipped@ on the day of the release.
1. Merge the release PR to `master`.
1. Make sure the dispatch workflow and copy workflows succeeded. E.g. ...
1. Wait for a bit and check how many unmerged PRs from web3-bot there are.
