### ISSUE TITLE
release check workflow doesn't trigger for PRs not targeting master

### ISSUE THREAD

**Issue by marten-seemann** [protocol/.github#329]
For example, here: https://github.com/libp2p/go-libp2p/blob/master/.github/workflows/release-check.yml

**Comment by galargh** [comment]
I cannot figure this one out. I tried to replicate the scenario where I created a PR to a non-default branch without modifying `version.json` and then modified `version.json` and pushed to the underlying branch but it all seems to work (https://github.com/galargh/.github/pull/20). 

Please let me know if you see it happening again. At the moment, all I can think of is that GitHub lost a webhook internally.

**Comment by galargh** [comment]
Closing since there were no newer reports and I wasn't able to reproduce :( Hopefully, some of the changes we did to the workflows in the meantime helped or it was just GitHub acting funny that one time.
