### ISSUE TITLE
Script to label all issues/PRs matching some query

### ISSUE THREAD

**Issue by Stebalien** [protocol/.github#40]
We occasionally need to go through and "fix" issue labels. It would be nice to have a script or a script framework where we could do things like: set `need/triage` on all issues lacking a `kind/` label.

**Comment by mvdan** [comment]
There are some actions in the github marketplace that do this sort of thing, but their configs tend to be rather stiff. I found one that applies PR labels based on files changed, or another that applies issue labels based on keywords.

I think a script would work fine here. You could even do it in Bash with a mix of https://github.com/cli/cli and `jq`, but another way would be to bite the bullet and use Go with either the REST or GraphQL client.

**Comment by galargh** [comment]
I recently created actions library that contains one to [find issues or pull requests by query](https://github.com/protocol/github-api-action-library/tree/master/find-content-by-query). I use it to find all the content that matches certain queries and add it to a project: https://github.com/galargh/.github/blob/master/.github/workflows/add-project-items.yml

We could definitely reuse it for this use case too. The query to find all issues without [kind labels](https://github.com/ipfs/community/blob/e0812a37d7a611bbf1f3b37b0bd00c017f98da8f/ISSUE_LABELS.md#kind) in all of our org would look something like that:
```
is:issue -label:kind/architecture,kind/bug,kind/discussion,kind/enhancement,kind/maintenance,kind/support,kind/test org:protocol org:ipfs org:ipfs-shipyard org:libp2p org:ipld org:multiformats
```

If we also add the action that updates issues with new labels to the library then we'll have all the building blocks there.
