### ISSUE TITLE
Add github action for nightly build

### ISSUE THREAD

**Issue by wemeetagain** [protocol/.github#409]
Now that we're adding package-lock files to some libraries (to preserve dev-ex), we need some way to quickly find breaking changes from dependency updates.

Some relevant links:
- https://github.com/protocol/.github/tree/master/templates/.github/workflows 
- https://github.com/protocol/.github/blob/master/configs/js.json

**Comment by galargh** [comment]
Hey, I don't think I quite grasp the idea behind this issue. Could you elaborate a bit on it?

**Comment by galargh** [comment]
This repo is going to get archived soon. Could you please re-raise the issue in https://github.com/pl-strflt/uci with a little description of the kind of nightly builds you're thinking of? I'll be happy to assist with setting it up :)
