### ISSUE TITLE
Go test -cover breaks certain tests

### ISSUE THREAD

**Issue by MarcoPolo** [protocol/.github#460]
I have a [test](https://github.com/libp2p/go-libp2p/pull/2044/files#diff-b1c5b5f77c1ee14eae450b69d05cd9f422859da177458a02783ee93ba7f01312R130) that I run to make sure a certain hot-path function doesn't allocate on the heap. I am unable to test this in CI because the coverage analysis adds a goroutine to the running test that does allocate in the background.

This commit (https://github.com/libp2p/go-libp2p/pull/2044/commits/e91b1e8f0d0ffbe6842a37925eb72e0177bf0773) disables the coverage analysis and tests pass. Before that commit: https://github.com/libp2p/go-libp2p/pull/2044/commits/82fc46754b915b2d498801465b9d5e983b9b0e69, tests would fail.

I do wonder if this could also be the cause of at least some flakiness we've see in CI? 

As for how to fix, I'm not sure. Maybe we should not use coverage analysis for the main `Go Test` workflow, and, instead, have a new workflow for coverage analysis that won't fail CI. Maybe even just do this for one platform rather than for all platforms as we do today. Not running coverage analysis saves us roughly a minute per workflow. By doing it one one platform we would shave 5 minutes off every CI run.

**Comment by MarcoPolo** [comment]
Marten also had the idea that we could do have a special build tag nocover, and then run go test again for only those tests. Slightly annoying though

**Comment by galargh** [comment]
The issue with coverage is also affecting https://github.com/filecoin-project/go-fil-commp-hashhash/pull/4. I think that's enough reason to introduce option to skip coverage altogether.

**Comment by galargh** [comment]
With https://github.com/protocol/.github/pull/472 merged to `next` branch, you can now disable coverage by modifying `GOTESTFLAGS` env var in `go-test-setup` action IF your repo follows [technical preview](https://github.com/protocol/.github#technical-preview) releases.
