### ISSUE TITLE
Better go linters

### ISSUE THREAD

**Issue by Jorropo** [protocol/.github#468]
It would be nice to setup golangci-lint with more linters (like `errcheck`).

The golangci-lint config could either be unified too, or let various repos enable linters they like (sounds more of a pain than anything).

For the list of linters, I think the best is to add them when needed, I would do:
- `staticcheck` (current, move to `golangci-lint`)
- `go vet` (current, move to `golangci-lint`)
- `errcheck` (new, see https://github.com/ipfs/go-unixfs/pull/133)

**Comment by galargh** [comment]
There were efforts to reimplement `errcheck` as part of the `staticcheck` framework - https://github.com/dominikh/go-tools/issues/23 - but it was ultimately deemed not a viable option and removed altogether - https://github.com/dominikh/go-tools/commit/6596888f3453f7af2ffa567a917e88783a457082. Given that, my initial thoughts are that it might be better to stick with `staticcheck` and `go vet` which are already executed as part of `go-check` workflow.

**Comment by galargh** [comment]
This issue was transferred to https://github.com/pl-strflt/uci/issues/47 in preparation for archiving of this repository.
