### ISSUE TITLE
default + required in reusable workflow seems to be broken

### ISSUE THREAD

**Issue by laurentsenta** [protocol/.github#469]
Raised by @rvagg in https://filecoinproject.slack.com/archives/C03KLC57LKB/p1676076582573909

We use a default + required value in [release-check.yml](https://github.com/protocol/.github/blob/6b6b0df89780dd14d499ee83b57afe40572be040/.github/workflows/release-check.yml#L8),
But it seems that this value is ignored: https://github.com/ipld/go-ipld-prime/actions/runs/4148548218.
Which breaks the release-check workflows for client repos until they upgrade.

Likely a one-time issue,

Reproduction:

- [config without required](https://github.com/laurentsenta/pl-dotgithub/blob/7af09622b400698bd74012143dcbcc1e04e21801/.github/workflows/release-check.yml#L6), called by [this file](https://github.com/laurentsenta/pl-github/blob/22f966ba332512316456f69a7bdfac4620895c17/.github/workflows/release-check.yml#L11), ends with a [success](https://github.com/laurentsenta/pl-github/actions/runs/4162466386/jobs/7201673083). The value defaulted to 1.19.x.
- [config with required](https://github.com/laurentsenta/pl-dotgithub/blob/93a62bd936b920636599b4e9cf401d578204f8d1/.github/workflows/release-check.yml#L6) failed with [missing input error](https://github.com/laurentsenta/pl-github/actions/runs/4162492393)

**Comment by laurentsenta** [comment]
@galargh flagging this to ensure we look into it when you're back.

**Comment by galargh** [comment]
https://github.com/laurentsenta/pl-dotgithub/blob/7af09622b400698bd74012143dcbcc1e04e21801/.github/workflows/release-check.yml#L6 <- this makes sense to me. Could you turn it into a PR?

**Comment by laurentsenta** [comment]
Could you confirm we want to remove that `required` flag?
I thought we'd fix it on a case-by-case basis and then remove the default value:
https://github.com/laurentsenta/pl-dotgithub/blob/7af09622b400698bd74012143dcbcc1e04e21801/.github/workflows/release-check.yml#L8

If we drop the required, we have to keep the default value.

**Comment by galargh** [comment]
> Could you confirm we want to remove that `required` flag? I thought we'd fix it on a case-by-case basis and then remove the default value: https://github.com/laurentsenta/pl-dotgithub/blob/7af09622b400698bd74012143dcbcc1e04e21801/.github/workflows/release-check.yml#L8
> 
> If we drop the `required` flag, we have to keep the default value.

That's fair enough. Let's keep it open until we upgrade everywhere but let's not take any action now.

**Comment by galargh** [comment]
With https://github.com/pl-strflt/uci and the complete overhaul of Unified CI workflows I think it's safe to close this.
