### ISSUE TITLE
Unified CI config update job broken on all js repos

### ISSUE THREAD

**Issue by achingbrain** [protocol/.github#478]
https://github.com/libp2p/github-mgmt/pull/93 defines the list of acceptable prefixes for PR titles - `feat:`, `fix:`, etc.

The Unified CI job runs with `sync:` which is not in that list so all the PRs it opened yesterday have failed CI - it should run with `chore:` instead.

go and rust repos will likely encounter the same problem when https://github.com/libp2p/github-mgmt/pull/125 is merged.

**Comment by galargh** [comment]
I'm on it 💪 https://github.com/protocol/.github/pull/476
