### ISSUE TITLE
Commit messages in auto-merged PRs do not follow conventional commits

### ISSUE THREAD

**Issue by achingbrain** [protocol/.github#498]
When Web3Bot PRs are merged, the commit message should follow the rules of conventional commits, otherwise the auto releases don't work properly.

See for example: https://github.com/ipfs/helia-ipns/commit/7558d38327946c7a926a89a968ec7cf2af43d4fb

The commit message is:

> update .github/workflows/js-test-and-release.yml

It should be:

> chore: update .github/workflows/js-test-and-release.yml

**Comment by galargh** [comment]
I think that all commits/PRs created from https://github.com/pl-strflt/uci should follow conventional commits syntax now.
