### ISSUE TITLE
Improve permissions

### ISSUE THREAD

**Issue by Stebalien** [protocol/.github#50]
We need more people to have write/approve access on this repo. Ideally, any SWE at PL could write, but we can restrict merge access to a group.

**Comment by marten-seemann** [comment]
@andyschwab, can you help us with that?

**Comment by andyschwab** [comment]
Got it! I've added `web3-dev-em` and `web3-dev-leads` as **admin**, added `labbers-ltc` with **write**, and restricted push to admins/maintainers only.

**Comment by Stebalien** [comment]
@andyschwab Sorry, I should have been more specific. The stewards team needs to be able to merge and currently can't.

**Comment by andyschwab** [comment]
Ahhh - I added `w3dt-stewards` team as admin, and removed the restriction that required admins to meet the reviews requirement
