### ISSUE TITLE
Disable codecov annotations on PRs 

### ISSUE THREAD

**Issue by lidel** [protocol/.github#503]
## Problem

I find myself burning time on single line diffs like ones below 
(you have to copy&paste because GH modifies url if i dont escape it):

- `https://github.com/ipfs/bifrost-gateway/pull/61/commits/7d4ae9ebb6aaf97b1b666edd5c0a55f5b1d71c0e`
- `https://github.com/ipfs/bifrost-gateway/pull/61/commits/7deef313157f71728d4868672539cdb7f6f77286`
- `https://github.com/ipfs/boxo/pull/176/commits/5f7a83313f98bef9f9bb6b1fb887fa20bf444a07` 
- `https://github.com/ipfs/bifrost-gateway/pull/61/files/efd4f1b0b4840471d855230a0418da8775a9ba38..d8bdf201d06f5e61a219f7b841ece0170763d160?diff=split&w=1` 

I feel I tuned out a long time ago, don't notice them at all, just like billboards next to the road.

The only impact they have on me is lowered productivity – a single line diff is a wall of text, so I have to check out code locally and diff there. 

## Proposal

Could we disable annotations on PRs to decrease the noise?

**Comment by galargh** [comment]
As it turns out you can control it on multiple levels (see https://docs.codecov.com/docs/github-checks#disabling-github-checks-patch-annotations):

- add 
    ```
    github_checks:
        annotations: false
    ``` 
    to `codecov.yaml` to disable annotation creation altogether
- hit `a` when you're browsing through the commits/PR to hide the annotations

**Comment by galargh** [comment]
I'm going to close this issue now since we can resolve it on per-repo basis.
