### ISSUE TITLE
Templating

### ISSUE THREAD

**Issue by Stebalien** [protocol/.github#57]
When trying to figure out how to deploy issue templates, I've realized that I need some level of templating. E.g.,

- The org's name.
- The org's security email.
- The repo's name.
- The repo's URL.

**Comment by marten-seemann** [comment]
What a coincidence. I just talked with @andyschwab and we decided to create different users for every org. That way, if one user gets compromised, the attacker can't take over *all* PL repos.
This also means that we'll have to use some kind of templating for the `autorebase` workflow.

**Comment by marten-seemann** [comment]
Simplest option: Use `%PLACEHOLDER%` in the yml template file, and then run `sed` in the copy workflow.

That doesn't scale very well though.

Do you have any suggestion for a more elegant solution?

**Comment by Stebalien** [comment]
`m4` or maybe go templates?
